package.json

Using the `bin` directive to specify an executable in your
package.json does not guarantee that once `npm pack` has been run the
files will be available.
This PR ensures the executables are there to put into .bin.

Ensure executables are in the packed build

---

packages/parse-profile/src/trace/cpuprofile.ts
packages/parse-profile/src/trace/export.ts
packages/parse-profile/src/trace/renderEvents.ts
packages/parse-profile/src/trace/trace.ts
packages/parse-profile/tests/aggregator-test.ts
packages/parse-profile/tests/cpu-profile-test.ts
packages/parse-profile/tests/generators.ts

**What it does**
This PR reads ember-perf-timeline component render events from the trace file if they are present and inserts them into the cpuprofile node hierarchy as dummy ICpuProfileNode's. The time aggregation algo has been adjusted to ignore them. These will be used in future PRs for more detailed time aggregations.
**How it does it**
I had originally thought I could just treat render event start/end points as fake samples and get them inserted in the same step as the profile expansion. However, to determine which node to place the event under, I had to know the end time of the node, and this isn't easily to know/pre-compute in a clean way when looking at single, un-expanded samples in sequence. I opted instead to insert render nodes after the profile expansion, and deal with all …

Insert render events as fake function slice nodes

---

packages/parse-profile/src/trace/cpuprofile.ts

We normally terminate a function slice when we see a sample which doesn't contain it (or the current v8.execute event ends). We allow the user to specify an end point for the analysis, and sometimes that endpoint may occur when a function is actively running. In order to handle this, this PR will terminate any active function slices once we hit the endpoint.

Terminate function slices at the end of trace correctly

---

packages/parse-profile/src/trace/cpuprofile.ts
packages/parse-profile/src/trace/renderEvents.ts

This gets rid of the null assertion operator use in the code base, which was used to asset that the hierarchy node's .children array was defined. When I create the hierarchy nodes I ensure that they have at least an empty array as children, but the D3 hierarchy type allows them to be undefined. I played around trying to extend the hierarchy node type and use that, but it had other annoying issues. In the end I just wrote an accessor function to the node's children array which throws an error if it's not defined.

Gets rid of null assertion operator use

---

packages/parse-profile/src/cli/analyze.ts
packages/parse-profile/src/cli/reporter.ts
packages/parse-profile/src/cli/utils.ts
packages/parse-profile/src/trace/export.ts
packages/parse-profile/src/trace/renderEvents.ts

During cmd line output phase, iterate over every render node and aggregate modules for each. This gives you one aggregation for the overall trace, and one aggregation with each render node as the root. Piping this output into a file is currently a poor-man's way of doing this analysis for any specific render node. In future PRs I will design both a more programatic way to ingesting the results (json output) as well as a more interactive UI that can be used to do this selectively on the fly.

Run aggregate on all render nodes

---

packages/cli/src/commands/compare.ts
packages/cli/src/helpers/default-flag-args.ts
packages/cli/src/helpers/flags.ts
packages/cli/src/helpers/simulate-device-options.ts
packages/cli/src/helpers/tb-config.ts
packages/cli/src/helpers/utils.ts
packages/cli/src/static/simulate-device-options.json
packages/cli/tsconfig.json
packages/tracerbench/src/benchmarks/initial-render.ts
packages/tracerbench/src/tab.ts

This feature uses the this json from [ChromeDevTools](https://github.com/ChromeDevTools/devtools-frontend/blob/51d3d758c57dc51d1864b3003de1fdda82963623/front_end/emulated_devices/module.json) to form the options. Each object in the "extensions" array attribute of the json contains settings such as screen size dimensions, and user-agent, and an accompanying device name such as iPhone 4.
We convert the name into a user typeable string so that we can match up a setting with the string when it comes time to parse which option the user wanted.

Emulate Mobile Device

---

.gitignore
packages/cli/README.md
packages/cli/src/commands/compare.ts
packages/cli/src/commands/create-archive.ts
packages/cli/src/commands/marker-timings.ts
packages/cli/src/commands/trace.ts
packages/cli/src/helpers/default-flag-args.ts
packages/cli/src/helpers/flags.ts
packages/cli/src/helpers/log-compare-results.ts
packages/cli/src/helpers/tb-config.ts
packages/cli/tb-schema.json
packages/cli/test/commands/compare.test.ts
packages/cli/test/commands/create-archive.ts
packages/cli/test/commands/marker-timings.test.ts
packages/cli/test/commands/trace.ts
packages/cli/test/helpers/log-compare-results.test.ts
packages/cli/test/tbconfig.json

Changing references of tbResultsFile to tbResultsFolder since we are using it as a folder path.

Renaming tbResultsFile -> tbResultsFolder

---

packages/cli/README.md
packages/cli/src/command-config/default-flag-args.ts
packages/cli/src/command-config/tb-config.ts
packages/cli/src/helpers/flags.ts
packages/cli/tb-schema.json

This PR:
- allows fidelity to accept an integer
- defaults the fidelity=high to 50 samples

feat(cli): fidelity accepts an int, bump high 50

---

packages/cli/README.md
packages/cli/src/command-config/default-flag-args.ts
packages/cli/src/commands/create-archive.ts
packages/cli/src/commands/trace.ts
packages/tracerbench/src/trace/archive_trace.ts
packages/tracerbench/src/trace/trace-utils.ts

In order to fix invalid certificate issues when generating har file in development, I modified packages/tracerbench/src/trace/trace-utils.ts to take in additional browser args and merge it with the default original set. I modified packages/cli/src/commands/create-archive.ts to pass the global default browser args which includes the ignore invalid certificate error flag
There also has been some refactoring where the parent functions are expected to write the har and cookie output

feat(tracerbench/trace-utils): Accept additional browser arguments

---

packages/cli/README.md
packages/cli/package.json
packages/cli/src/commands/compare.ts
packages/cli/src/commands/report.ts
packages/cli/src/commands/trace.ts
packages/cli/src/helpers/create-consumable-html.ts
packages/cli/src/helpers/flags.ts
packages/cli/src/helpers/log-compare-results.ts
packages/cli/src/helpers/table.ts
packages/cli/test/commands/compare.test.ts
packages/cli/test/commands/report.test.ts
packages/cli/test/helpers/log-compare-results.test.ts

The goal of these changes are to provide a similar experience as the pdf artifact but in the terminal output.
I refactored logCompareResults to use the same functions that createConsumeableHTML uses to prepare its data. I left the original tables intact but made some changes to the summary at the bottom.
- Removed the "js" section
- Removed the JSON dump of the results generated from logCompareResults
Original
Sample when phases are insignificant
Sample when phases are significant

Refactoring the output of the "compare" command

---

packages/cli/README.md
packages/cli/package.json
packages/cli/src/command-config/tb-config.ts
packages/cli/src/commands/compare/analyze.ts
packages/cli/src/commands/compare/index.ts
packages/cli/src/helpers/create-consumable-html.ts
packages/cli/src/helpers/log-compare-results.ts
packages/cli/src/helpers/table.ts
packages/cli/tb-schema.json
packages/cli/test/commands/compare.test.ts
packages/cli/test/commands/report.test.ts
packages/cli/test/helpers/log-compare-results.test.ts
yarn.lock

This PR address the existing bug with the compare command --json flag. Additionally includes dep bumps and additional tests.
Additionally this PR allows for the compare command to return JSON as the default without the need to explicitly include the `--json` flag

fix: fixing compare cmd to include json return

---

packages/cli/src/command-config/index.ts
packages/cli/src/command-config/tb-base.ts
packages/cli/src/commands/compare/analyze.ts
packages/cli/src/commands/compare/index.ts
packages/cli/src/commands/create-archive.ts
packages/cli/src/commands/marker-timings.ts
packages/cli/src/commands/report.ts
packages/cli/src/commands/trace.ts
packages/cli/src/helpers/log-compare-results.ts
packages/cli/test/helpers/log-compare-results.test.ts

This PR will set us up to refactor redundant setup code within each command into a single base command which is then extended for children commands. 
Additionally this will set us up to succinctly implement `pre-req()` checks centralized without redundancy.

feat(cli): tracerbench base cmd

---

packages/cli/src/helpers/create-consumable-html.ts
packages/cli/src/index.ts
packages/cli/test/helpers/create-consumable-html.test.ts
packages/cli/tslint.json

Refactoring the `createConsumeableHTML` function to extract our the portion that formats the data for the HTML template. That new function is called `generateDataForHTML` and will be exposed to other libraries if TB is installed as a lib.

refactor(create-consumable-html): Making HTML Data Formatter Reusable

---

packages/core/src/run.ts
packages/core/src/util/gc.ts

Dynamically get the gc function so that a user doesn't need to set --expose-gc since this is hard to do with the CLI.

feat: collect garbage between samples

---

packages/cli/test/compare/generate-stats.test.ts
packages/stats/src/confidence-interval.ts
packages/stats/src/stats.ts
packages/stats/test/confidence-interval.test.ts
packages/stats/tsconfig.json
packages/stats/types/jstat/index.d.ts

Add pValue and zScore and unify test in preparation for adding quality rating to test result to aid in determining how borderline evidence is.

feat: add pValue and zScore

---

packages/cli/src/compare/generate-stats.ts
packages/cli/src/compare/tb-table.ts
packages/cli/test/compare/generate-stats.test.ts
packages/stats/src/index.ts
packages/stats/src/stats.ts
packages/stats/src/utils.ts
packages/stats/test/stats.test.ts

This PR includes the functionality to pass a unit conversion function during instantiation of the Stats class. Critically this conversion happens after statistical calculations as we need to guarantee ties are correctly handled with the raw data.

feat(stats): opt unitConverterFn in Stat constructor

---

packages/cli/src/commands/compare/report.ts
packages/cli/src/compare/compare-results.ts
packages/cli/src/compare/generate-stats.ts
packages/cli/src/compare/tb-table.ts
packages/cli/src/static/phase-detail-partial.hbs
packages/stats/src/stats.ts

This PR provides the following functionality:
- expose pvalue evidence in pdf/html reports (very strong, strong or weak)
- expose pvalue in stdout report
- isSig includes p-val < 5%
Additionally adds the following language to the pdf/html reports:
```
Based on the P-value of this benchmark the evidence for a metric shift is very strong. TracerBench has
determined the results are significant meaning they are worth looking at. A statistics estimator 
(Hodges–Lehmann estimator) was used to determine "Experiment" is slower by 1011 ms. TracerBench 
is 95% confident "Experiment" is slower between 1008 ms to 1014 ms based on 10 samples 
using a (confidence interval).
```
```
ember (No/Borderline Difference)
Based on the P-value of this benchmark the evidence for a metric shift is weak. …
```

feat(cli): expose pvalue and evidence in reports

---

packages/stats/src/stats.ts
packages/stats/test/stats.test.ts

The significance level should be dynamically derived from the confidence level users configure.

fix: should use dynamic confidence level to calculate significance

---

packages/cli/package.json
packages/cli/src/compare/index.ts
packages/cli/src/helpers/index.ts
packages/stats/src/index.ts
yarn.lock

1. Expose utility APIs for consumer library to create customized HTML and PDF reports. 
2. Upgrade to 6.1.0 type definition for html-minifier-terser. 
Validated all tests passed on Mac and Linux.

feat: export APIs for rich report generation

---

packages/cli/src/commands/record-har/index.ts

fixes:
Error: Error: ProtocolError: At least one of the url or domain needs to be
specified. CookieParam format invalid: https://chromedevtools.github.io/d
evtools-protocol/tot/Network#type-CookieParam.
for default cookie fallback (if no file provided)
https://github.com/TracerBench/tracerbench/issues/338#issuecomment-870559516

fixes empty cookie error
